### ISSUE TITLE
fetch http adapter

### ISSUE THREAD

**Issue by chloe7303** [yarchiee/Personal_Project#7]
Is your feature request related to a problem? Please describe.
The largest driving factor for this adapter is to honor the maxRedirects setting in the browser. This issue was previously raised and closed multiple times:

issue https://github.com/axios/axios/issues/674
issue https://github.com/axios/axios/issues/1227
issue https://github.com/axios/axios/issues/3924
Describe the solution you'd like
Include a fetch http adapter (perhaps with coordination from https://github.com/vespaiach/axios-fetch-adapter). To ensure support for browsers that don't support fetch, a factory could load the appropriate adapter.

And of course, part of adding the fetch adapter would be to honor the maxRedirects settings.

Describe alternatives you've considered
Currently the alternatives in the issues that have been previously closed are to not use axios at all and to use fetch instead. I have had to resort to this, but it has become cumbersome to manage especially when there are features of axios that can't be leveraged and causes for awkward maintenance of the code.

**Comment by yarchiee** [comment]
@yarchiee

**Comment by yarchiee** [comment]
@chloe7303

**Comment by elaine011** [comment]
一下

**Comment by elaine011** [comment]
axios讚讚

**Comment by elaine011** [comment]
推薦octokit

**Comment by yarchiee** [comment]
zxcxcv

**Comment by yarchiee** [comment]
zxcxcv

**Comment by yarchiee** [comment]
sdfsdf

**Comment by yarchiee** [comment]
sdfsdf

**Comment by yarchiee** [comment]
sdfsdf

**Comment by yarchiee** [comment]
sdfsdf

**Comment by yarchiee** [comment]
sdf

**Comment by yarchiee** [comment]
sdf

**Comment by yarchiee** [comment]
sdf

**Comment by yarchiee** [comment]
sdf

**Comment by yarchiee** [comment]
dfgdgdfg

**Comment by yarchiee** [comment]
vgjvhj

**Comment by yarchiee** [comment]
vgjvhj

**Comment by yarchiee** [comment]
vgjvhjxcvx

**Comment by yarchiee** [comment]
dfgdftf

**Comment by yarchiee** [comment]
564987

**Comment by yarchiee** [comment]
qazqaz

**Comment by yarchiee** [comment]
new

**Comment by yarchiee** [comment]
create
